import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import NavBar from '@/sections/Navbar';
import NavBarHead from '@/sections/NavbarHead';
import '@/lib/fontawesome'; // ✅ path to the file you created

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Next Store',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NavBarHead />
        <NavBar />
        {children}
      </body>
    </html>
  );
}
