import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import NavBar from '@/sections/Navbar';
import { CartProvider } from './context/CartContext';
import '@/lib/fontawesome'; // ✅ path to the file you created
import ConditionalLogo from '@/components/ConditionalLogo';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Next Store',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo-16x16.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <CartProvider>
          <NavBar />
          {/* <ConditionalLogo /> */}
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
